# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=100, verbose_name=b'Email Host')),
                ('email_port', models.SmallIntegerField(default=25, verbose_name=b'Email Port')),
                ('email_from_email', models.CharField(max_length=50, verbose_name=b'Default From Email')),
                ('email_host_user', models.CharField(max_length=50, verbose_name=b'Email User')),
                ('email_host_password', models.CharField(max_length=50, verbose_name=b'Email User Password')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name=b'Use TLS?')),
                ('email_fail_silently', models.BooleanField(default=False, verbose_name=b'Fail Silently?')),
                ('email_timeout', models.SmallIntegerField(default=60, verbose_name=b'Email Send Timeout')),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
    ]
