# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('django_des', '0001_initial'), ('django_des', '0002_dynamicemailconfiguration_email_use_ssl'), ('django_des', '0003_auto_20171207_1935'), ('django_des', '0004_auto_20171207_2142'), ('django_des', '0005_auto_20171207_2151')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(default='localhost', max_length=256, verbose_name='Email Host')),
                ('email_port', models.SmallIntegerField(default=25, verbose_name='Email Port')),
                ('email_from_email', models.CharField(default='django@localhost', max_length=256, verbose_name='Default From Email')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=256, verbose_name='Email User')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=256, verbose_name='Email User Password')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='Use TLS?')),
                ('email_fail_silently', models.BooleanField(default=False, verbose_name='Fail Silently?')),
                ('email_timeout', models.SmallIntegerField(default=60, verbose_name='Email Send Timeout (seconds)')),
                ('email_use_ssl', models.BooleanField(default=False, verbose_name='Use SSL?')),
            ],
            options={
                'verbose_name': 'Email Configuration',
            },
        ),
    ]
