# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_des', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicemailconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name=b'Use SSL?'),
        ),
    ]
