# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_des', '0001_squashed_0005_auto_20171207_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_fail_silently',
            field=models.BooleanField(default=False, verbose_name='Fail Silently'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_from_email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Default From Email'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Email Host'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Email User Password'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Email User'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_port',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Email Port'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_timeout',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Email Send Timeout (seconds)'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Use SSL'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=False, verbose_name='Use TLS'),
        ),
    ]
