# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_des', '0002_dynamicemailconfiguration_email_use_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False, verbose_name=b'Use SSL? (Requires EMAIL_SSL_CERTFILE and EMAIL_SSL_KEYFILE to be defined in settings.py)'),
        ),
    ]
