# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_des', '0004_auto_20171207_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_from_email',
            field=models.CharField(default='django@localhost', max_length=256, verbose_name='Default From Email'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host',
            field=models.CharField(default='localhost', max_length=256, verbose_name='Email Host'),
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Email User Password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dynamicemailconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Email User'),
            preserve_default=False,
        ),
    ]
